project:
  type: website

website:
  title: "MITNB"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - text: "Literature"
        href: literature/index.qmd
      - text: "People"
        href: people/index.qmd
    # right:
      # - icon: 



format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

