project:
  type: website
  output-dir: docs

website:
  title: "Measurement Is The New Black"
  image: files/images/logo_mitnb.png

  navbar:
    background: primary
    search: true
    left:
      - text: "{{< fa house >}} Home"
        file: index.qmd
      # - text: "{{< fa brands slack >}} Slack"
        # file: extra/slack.qmd
      - text: "{{< fa circle-info >}} About"
        file: about/index.qmd
      - text: "{{< fa book >}} Literature"
        href: literature/index.qmd
      - text: "{{< fa people-group >}} People"
        href: people/index.qmd
      - text: "{{< fa list-ul >}} Projects"
        href: projects/index.qmd
    right:
      - icon: envelope
        text: Email us
        href: "mailto:l.f.bringmann@rug.nl"
      
  page-footer:
    left: |
       <span class="faux-block">{{< fa brands creative-commons >}} 2023 MITNB</span>
       <span class="faux-block"> Built with <a href="https://quarto.org/">Quarto</a></span>
       
    center: |
        <span class="faux-block"><a href="https://github.com/bsiepe/mitnb-website">{{< fa brands github >}} Source Code</a></span>
        <span class="faux-block"><a href="https://github.com/bsiepe/mitnb-website">{{< ai osf >}} OSF </a></span>
    # right:
    #   - text: "Impressum"
    #     href: extra/impressum.qmd
    #   - text: "Data Privacy"
    #     href: extra/data_privacy.qmd
       
 



format:
  html:
    theme: 
      - litera
      - styles.css
    toc: true
    page-layout: full
    fontsize: 1.1em

editor: visual

